### ISSUE TITLE
Add MySQL DB creation to main()

### ISSUE THREAD

**Issue by JoshHarmon** [pkill37/mybb-shetup#6]
The DB function hasn't been added to main yet. It still needs to validate that mysql is at a place in $PATH, else we need to ask the user for a path to it.

Assigning myself to the task, since that was my little addon.

**Comment by pkill37** [comment]
Cool. There are other things yet to be added to `main()`, but those things are still kinda half-baked.

Also, I was considering renaming `database_create()` to `mysql_setup()` since it's MySQL-specific and we're not just creating a database, but also setting up a few other things. Any thoughts on that?

**Comment by JoshHarmon** [comment]
I'll add that to my list of things to do. I'll do that since I am not a git ninja with respects to the git stash command. Things never go right for me!

**Comment by JoshHarmon** [comment]
See 9c62bf98316c4f962af2c021f1ea70c4b0e5154d after my reverts of reverts of reverts on my Mac. Some code may be broken.

**Comment by JoshHarmon** [comment]
9c62bf9 causes script to exit without asking anything of the user in the mysql_setup part.

**Comment by pkill37** [comment]
@JoshH99 What's the status on this?

**Comment by JoshHarmon** [comment]
@faviouz Probably going to end up scrapping the function and starting it anew.
